CREATE TABLE users
(
    user_id INT GENERATED BY DEFAULT AS IDENTITY constraint users_pk primary key,
    username VARCHAR(36) UNIQUE not null ,
    password  VARCHAR(255) not null,
    isAccountNonExpired BOOLEAN,
    isAccountNonLocked BOOLEAN,
    isCredentialsNonExpired BOOLEAN,
    isEnabled BOOLEAN,
    created_at TIMESTAMP,
    updated_at  TIMESTAMP
);

