create table friendships(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    requestFrom VARCHAR(36) not null,
    requestTo VARCHAR(36) not null,
    status VARCHAR(36) not null,
    endedBy VARCHAR(36) not null DEFAULT(null),
    created_at TIMESTAMP,
    updated_at  TIMESTAMP,
    constraint friendships_pk primary key (requestFrom, requestTo)
);

alter table friendships
    add constraint friendships_requestFrom_fk
        foreign key (requestFrom)
            references users(username) on delete cascade;

alter table friendships
    add constraint friendships_requestTo_fk
        foreign key (requestTo)
            references users(username) on delete cascade;



